### ISSUE TITLE
"Image not found" error when trying to preview site

### ISSUE THREAD

**Issue by redmondo** [koenbok/Cactus#176]
I'm pasting in the error report I'm getting when trying to preview my site locally.

I'm using the recent beta of OS X, and I'm not sure if the below is related.

Any ideas?

```
Traceback (most recent call last):
File "/Applications/Cactus.app/Contents/Resources/python/run.py", line 32, in <module>
from cactus import cli
File "/Applications/Cactus.app/Contents/Resources/python/CactusSource/cactus/__init__.py", line 4, in <module>
from cactus.site import Site
File "/Applications/Cactus.app/Contents/Resources/python/CactusSource/cactus/site.py", line 32, in <module>
from cactus.listener import Listener
File "/Applications/Cactus.app/Contents/Resources/python/CactusSource/cactus/listener/__init__.py", line 7, in <module>
from mac import FSEventsListener
File "/Applications/Cactus.app/Contents/Resources/python/CactusSource/cactus/listener/mac.py", line 33, in <module>
libc = CDLL('libc.dylib')
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 365, in __init__
self._handle = _dlopen(self._name, mode)
OSError: dlopen(libc.dylib, 6): image not found
```

**Comment by mikejohnstn** [comment]
I'm seeing the same thing (also using El Capitan beta). It also happens when trying to deploy.

**Comment by krallin** [comment]
Do you have either  `DYLD_LIBRARY_PATH` or `DYLD_FALLBACK_LIBRARY_PATH` set in your environment?

**Comment by mikejohnstn** [comment]
@krallin I don't, no. I tried setting `DYLD_FALLBACK_LIBRARY_PATH` to `/usr/lib` in my `.bash_profile` and restarting Cactus, but that didn't help.

**Comment by krallin** [comment]
@mikejohnstn  Do you have a `/usr/lib/libc.dylib`?

**Comment by mikejohnstn** [comment]
@krallin I do, yep.

**Comment by krallin** [comment]
@mikejohnstn 

Did you make sure to restart your bash session after updating your bash profile? If not, you might want to just do:

    export DYLD_FALLBACK_LIBRARY_PATH=/usr/lib 
   cactus serve 

And paste your CLI and its output?

**Comment by mikejohnstn** [comment]
Ah, I should've mentioned I was using the App Store version. So it's probably a sandboxing issue.

I just tried it from the command line after an `easy_install` and it works fine (no need for `DYLD_FALLBACK_LIBRARY_PATH`.

**Comment by krallin** [comment]
Ha. Unfortunately I don't actually have access to that code, so this is going to be an issue for @koenbok . He mentioned possibly open-sourcing it, but until then, I can't really help.

I'm sorry : (

**Comment by mikejohnstn** [comment]
@krallin No prob. If anyone else encounters this, all you need to do in the meantime is follow the instructions in the repo to install the command line version, and use that: https://github.com/koenbok/Cactus/

**Comment by aeyoa** [comment]
Faced the same issue on El Capitan as @redmondo. For now will use command line version. Thanks for the help, guys!
