### ISSUE TITLE
FSEventListener exception

### ISSUE THREAD

**Issue by alfetopito** [koenbok/Cactus#194]
Hey there,

I'm on Ubuntu 14.04. I installed Cactus 3.2.0 via pip on both python 3.4.3 and 2.7.9 and every time I run the `cactus` command this is printed:

```
Failed to load FSEventsListener
Traceback (most recent call last):
  File "/home/alfeto/.virtualenvs/cactus/lib/python2.7/site-packages/cactus/listener/__init__.py", line 11, in <module>
    from cactus.listener.mac import FSEventsListener as Listener
  File "/home/alfeto/.virtualenvs/cactus/lib/python2.7/site-packages/cactus/listener/mac.py", line 12, in <module>
    from fsevents import Observer, Stream
ImportError: No module named fsevents
```

Still, everything seems to work fine.

**Comment by krallin** [comment]
Yeah, this is actually just a warning (hence why everything works properly). That's... not ideal. We can probably make this clearer.

**Comment by krallin** [comment]
https://github.com/koenbok/Cactus/commit/63f8f15d359fd12827ef41def4faf72a5e998640
