### ISSUE TITLE
Python3: Tornado cannot be installed as requirement for Cactus

### ISSUE THREAD

**Issue by kartoch** [koenbok/Cactus#196]
Trying to install Cactus with dependencies:

    $ virtualenv-3.5 virtualenv
    Using base prefix '/usr'
    New python executable in virtualenv/bin/python3
    Also creating executable in virtualenv/bin/python
    Installing setuptools, pip, wheel...done.
    $ source virtualenv/bin/activate
    $ pip install -r requirements.txtpip install -r requirements.txt
    [...]
      copying build/lib.linux-x86_64-3.5/tornado/wsgi.py -> build/bdist.linux-x86_64/wheel/tornado
      running install_egg_info
      running egg_info
      writing tornado.egg-info/PKG-INFO
      writing top-level names to tornado.egg-info/top_level.txt
      writing dependency_links to tornado.egg-info/dependency_links.txt
      warning: manifest_maker: standard file '-c' not found
      
      reading manifest file 'tornado.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      no previously-included directories found matching 'docs/build'
      warning: no files found matching 'tornado/test/README'
      writing manifest file 'tornado.egg-info/SOURCES.txt'
      Copying tornado.egg-info to build/bdist.linux-x86_64/wheel/tornado-4.2.1-py3.5.egg-info
      running install_scripts
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/tmp/pip-build-so062v0_/tornado/setup.py", line 173, in <module>
          **kwargs
        File "/usr/lib64/python3.5/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/lib64/python3.5/distutils/dist.py", line 955, in run_commands
          self.run_command(cmd)
        File "/usr/lib64/python3.5/distutils/dist.py", line 974, in run_command
          cmd_obj.run()
        File "/home/kartoch/Documents/works/python/Cactus/virtualenv/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 213, in run
          archive_basename = self.get_archive_basename()
        File "/home/kartoch/Documents/works/python/Cactus/virtualenv/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 161, in get_archive_basename
          impl_tag, abi_tag, plat_tag = self.get_tag()
        File "/home/kartoch/Documents/works/python/Cactus/virtualenv/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 155, in get_tag
          assert tag == supported_tags[0]
      AssertionError
      
      ----------------------------------------
      Failed building wheel for tornado

I understand this is not directly related to Cactus, but It seems strange that py35 can be marked as "tested plaform" in f8f905244332adbd16a86f34e6f8cbfe921f3a0c with this problem still present.

**Comment by krallin** [comment]
First, I'm not sure this error message is fatal. For reference, here's what I get when I install Cactus' requirements in a Python 3.5 virtual environment:

```
Collecting Django<1.7,>=1.6 (from -r requirements.txt (line 1))
  Using cached Django-1.6.11-py2.py3-none-any.whl
Collecting django-markwhat<2,>=1.4 (from -r requirements.txt (line 2))
Collecting markdown2 (from -r requirements.txt (line 3))
Collecting argparse (from -r requirements.txt (line 4))
  Using cached argparse-1.4.0-py2.py3-none-any.whl
Collecting keyring (from -r requirements.txt (line 5))
  Downloading keyring-5.6.tar.gz (69kB)
    100% |████████████████████████████████| 69kB 1.0MB/s 
Collecting boto>=2.4.1 (from -r requirements.txt (line 6))
  Using cached boto-2.38.0-py2.py3-none-any.whl
Collecting tornado>=3.2 (from -r requirements.txt (line 7))
  Using cached tornado-4.2.1.tar.gz
Collecting colorlog (from -r requirements.txt (line 8))
  Using cached colorlog-2.6.0-py2.py3-none-any.whl
Collecting colorama (from -r requirements.txt (line 9))
Collecting six>=1.9.0 (from -r requirements.txt (line 10))
  Downloading six-1.10.0-py2.py3-none-any.whl
Building wheels for collected packages: keyring, tornado
  Running setup.py bdist_wheel for keyring
  Stored in directory: /Users/thomas/Library/Caches/pip/wheels/aa/05/ff/4ba3460c1807544fab90e6648937a68f855fed03d8090ce329
  Running setup.py bdist_wheel for tornado
  Complete output from command /Users/thomas/.virtualenvs/tmp-d2a50d26066a1de6/bin/python3.5 -c "import setuptools;__file__='/private/var/folders/vy/8gzkm2vj3w72v56yhs6wnmcm0000gn/T/pip-build-uto13tkj/tornado/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /var/folders/vy/8gzkm2vj3w72v56yhs6wnmcm0000gn/T/tmppscvor21pip-wheel-:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.10-x86_64-3.5
  creating build/lib.macosx-10.10-x86_64-3.5/tornado
  copying tornado/__init__.py -> build/lib.macosx-10.10-x86_64-3.5/tornado
  copying tornado/auth.py -> build/lib.macosx-10.10-x86_64-3.5/tornado
  copying tornado/autoreload.py -> build/lib.macosx-10.10-x86_64-3.5/tornado
  copying tornado/concurrent.py -> build/lib.macosx-10.10-x86_64-3.5/tornado
  copying tornado/curl_httpclient.py -> build/lib.macosx-10.10-x86_64-3.5/tornado
  copying tornado/escape.py -> build/lib.macosx-10.10-x86_64-3.5/tornado
  copying tornado/gen.py -> build/lib.macosx-10.10-x86_64-3.5/tornado
  copying tornado/http1connection.py -> build/lib.macosx-10.10-x86_64-3.5/tornado
  copying tornado/httpclient.py -> build/lib.macosx-10.10-x86_64-3.5/tornado
  copying tornado/httpserver.py -> build/lib.macosx-10.10-x86_64-3.5/tornado
  copying tornado/httputil.py -> build/lib.macosx-10.10-x86_64-3.5/tornado
  copying tornado/ioloop.py -> build/lib.macosx-10.10-x86_64-3.5/tornado
  copying tornado/iostream.py -> build/lib.macosx-10.10-x86_64-3.5/tornado
  copying tornado/locale.py -> build/lib.macosx-10.10-x86_64-3.5/tornado
  copying tornado/locks.py -> build/lib.macosx-10.10-x86_64-3.5/tornado
  copying tornado/log.py -> build/lib.macosx-10.10-x86_64-3.5/tornado
  copying tornado/netutil.py -> build/lib.macosx-10.10-x86_64-3.5/tornado
  copying tornado/options.py -> build/lib.macosx-10.10-x86_64-3.5/tornado
  copying tornado/process.py -> build/lib.macosx-10.10-x86_64-3.5/tornado
  copying tornado/queues.py -> build/lib.macosx-10.10-x86_64-3.5/tornado
  copying tornado/simple_httpclient.py -> build/lib.macosx-10.10-x86_64-3.5/tornado
  copying tornado/stack_context.py -> build/lib.macosx-10.10-x86_64-3.5/tornado
  copying tornado/tcpclient.py -> build/lib.macosx-10.10-x86_64-3.5/tornado
  copying tornado/tcpserver.py -> build/lib.macosx-10.10-x86_64-3.5/tornado
  copying tornado/template.py -> build/lib.macosx-10.10-x86_64-3.5/tornado
  copying tornado/testing.py -> build/lib.macosx-10.10-x86_64-3.5/tornado
  copying tornado/util.py -> build/lib.macosx-10.10-x86_64-3.5/tornado
  copying tornado/web.py -> build/lib.macosx-10.10-x86_64-3.5/tornado
  copying tornado/websocket.py -> build/lib.macosx-10.10-x86_64-3.5/tornado
  copying tornado/wsgi.py -> build/lib.macosx-10.10-x86_64-3.5/tornado
  creating build/lib.macosx-10.10-x86_64-3.5/tornado/test
  copying tornado/test/__init__.py -> build/lib.macosx-10.10-x86_64-3.5/tornado/test
  copying tornado/test/__main__.py -> build/lib.macosx-10.10-x86_64-3.5/tornado/test
  copying tornado/test/asyncio_test.py -> build/lib.macosx-10.10-x86_64-3.5/tornado/test
  copying tornado/test/auth_test.py -> build/lib.macosx-10.10-x86_64-3.5/tornado/test
  copying tornado/test/concurrent_test.py -> build/lib.macosx-10.10-x86_64-3.5/tornado/test
  copying tornado/test/curl_httpclient_test.py -> build/lib.macosx-10.10-x86_64-3.5/tornado/test
  copying tornado/test/escape_test.py -> build/lib.macosx-10.10-x86_64-3.5/tornado/test
  copying tornado/test/gen_test.py -> build/lib.macosx-10.10-x86_64-3.5/tornado/test
  copying tornado/test/httpclient_test.py -> build/lib.macosx-10.10-x86_64-3.5/tornado/test
  copying tornado/test/httpserver_test.py -> build/lib.macosx-10.10-x86_64-3.5/tornado/test
  copying tornado/test/httputil_test.py -> build/lib.macosx-10.10-x86_64-3.5/tornado/test
  copying tornado/test/import_test.py -> build/lib.macosx-10.10-x86_64-3.5/tornado/test
  copying tornado/test/ioloop_test.py -> build/lib.macosx-10.10-x86_64-3.5/tornado/test
  copying tornado/test/iostream_test.py -> build/lib.macosx-10.10-x86_64-3.5/tornado/test
  copying tornado/test/locale_test.py -> build/lib.macosx-10.10-x86_64-3.5/tornado/test
  copying tornado/test/locks_test.py -> build/lib.macosx-10.10-x86_64-3.5/tornado/test
  copying tornado/test/log_test.py -> build/lib.macosx-10.10-x86_64-3.5/tornado/test
  copying tornado/test/netutil_test.py -> build/lib.macosx-10.10-x86_64-3.5/tornado/test
  copying tornado/test/options_test.py -> build/lib.macosx-10.10-x86_64-3.5/tornado/test
  copying tornado/test/process_test.py -> build/lib.macosx-10.10-x86_64-3.5/tornado/test
  copying tornado/test/queues_test.py -> build/lib.macosx-10.10-x86_64-3.5/tornado/test
  copying tornado/test/resolve_test_helper.py -> build/lib.macosx-10.10-x86_64-3.5/tornado/test
  copying tornado/test/runtests.py -> build/lib.macosx-10.10-x86_64-3.5/tornado/test
  copying tornado/test/simple_httpclient_test.py -> build/lib.macosx-10.10-x86_64-3.5/tornado/test
  copying tornado/test/stack_context_test.py -> build/lib.macosx-10.10-x86_64-3.5/tornado/test
  copying tornado/test/tcpclient_test.py -> build/lib.macosx-10.10-x86_64-3.5/tornado/test
  copying tornado/test/tcpserver_test.py -> build/lib.macosx-10.10-x86_64-3.5/tornado/test
  copying tornado/test/template_test.py -> build/lib.macosx-10.10-x86_64-3.5/tornado/test
  copying tornado/test/testing_test.py -> build/lib.macosx-10.10-x86_64-3.5/tornado/test
  copying tornado/test/twisted_test.py -> build/lib.macosx-10.10-x86_64-3.5/tornado/test
  copying tornado/test/util.py -> build/lib.macosx-10.10-x86_64-3.5/tornado/test
  copying tornado/test/util_test.py -> build/lib.macosx-10.10-x86_64-3.5/tornado/test
  copying tornado/test/web_test.py -> build/lib.macosx-10.10-x86_64-3.5/tornado/test
  copying tornado/test/websocket_test.py -> build/lib.macosx-10.10-x86_64-3.5/tornado/test
  copying tornado/test/wsgi_test.py -> build/lib.macosx-10.10-x86_64-3.5/tornado/test
  creating build/lib.macosx-10.10-x86_64-3.5/tornado/platform
  copying tornado/platform/__init__.py -> build/lib.macosx-10.10-x86_64-3.5/tornado/platform
  copying tornado/platform/asyncio.py -> build/lib.macosx-10.10-x86_64-3.5/tornado/platform
  copying tornado/platform/auto.py -> build/lib.macosx-10.10-x86_64-3.5/tornado/platform
  copying tornado/platform/caresresolver.py -> build/lib.macosx-10.10-x86_64-3.5/tornado/platform
  copying tornado/platform/common.py -> build/lib.macosx-10.10-x86_64-3.5/tornado/platform
  copying tornado/platform/epoll.py -> build/lib.macosx-10.10-x86_64-3.5/tornado/platform
  copying tornado/platform/interface.py -> build/lib.macosx-10.10-x86_64-3.5/tornado/platform
  copying tornado/platform/kqueue.py -> build/lib.macosx-10.10-x86_64-3.5/tornado/platform
  copying tornado/platform/posix.py -> build/lib.macosx-10.10-x86_64-3.5/tornado/platform
  copying tornado/platform/select.py -> build/lib.macosx-10.10-x86_64-3.5/tornado/platform
  copying tornado/platform/twisted.py -> build/lib.macosx-10.10-x86_64-3.5/tornado/platform
  copying tornado/platform/windows.py -> build/lib.macosx-10.10-x86_64-3.5/tornado/platform
  creating build/lib.macosx-10.10-x86_64-3.5/tornado/test/csv_translations
  copying tornado/test/csv_translations/fr_FR.csv -> build/lib.macosx-10.10-x86_64-3.5/tornado/test/csv_translations
  creating build/lib.macosx-10.10-x86_64-3.5/tornado/test/gettext_translations
  creating build/lib.macosx-10.10-x86_64-3.5/tornado/test/gettext_translations/fr_FR
  creating build/lib.macosx-10.10-x86_64-3.5/tornado/test/gettext_translations/fr_FR/LC_MESSAGES
  copying tornado/test/gettext_translations/fr_FR/LC_MESSAGES/tornado_test.mo -> build/lib.macosx-10.10-x86_64-3.5/tornado/test/gettext_translations/fr_FR/LC_MESSAGES
  copying tornado/test/gettext_translations/fr_FR/LC_MESSAGES/tornado_test.po -> build/lib.macosx-10.10-x86_64-3.5/tornado/test/gettext_translations/fr_FR/LC_MESSAGES
  copying tornado/test/options_test.cfg -> build/lib.macosx-10.10-x86_64-3.5/tornado/test
  creating build/lib.macosx-10.10-x86_64-3.5/tornado/test/static
  copying tornado/test/static/robots.txt -> build/lib.macosx-10.10-x86_64-3.5/tornado/test/static
  creating build/lib.macosx-10.10-x86_64-3.5/tornado/test/static/dir
  copying tornado/test/static/dir/index.html -> build/lib.macosx-10.10-x86_64-3.5/tornado/test/static/dir
  copying tornado/test/static_foo.txt -> build/lib.macosx-10.10-x86_64-3.5/tornado/test
  creating build/lib.macosx-10.10-x86_64-3.5/tornado/test/templates
  copying tornado/test/templates/utf8.html -> build/lib.macosx-10.10-x86_64-3.5/tornado/test/templates
  copying tornado/test/test.crt -> build/lib.macosx-10.10-x86_64-3.5/tornado/test
  copying tornado/test/test.key -> build/lib.macosx-10.10-x86_64-3.5/tornado/test
  running build_ext
  building 'tornado.speedups' extension
  creating build/temp.macosx-10.10-x86_64-3.5
  creating build/temp.macosx-10.10-x86_64-3.5/tornado
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c tornado/speedups.c -o build/temp.macosx-10.10-x86_64-3.5/tornado/speedups.o
  clang -bundle -undefined dynamic_lookup build/temp.macosx-10.10-x86_64-3.5/tornado/speedups.o -o build/lib.macosx-10.10-x86_64-3.5/tornado/speedups.cpython-35m-darwin.so
  installing to build/bdist.macosx-10.10-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.macosx-10.10-x86_64
  creating build/bdist.macosx-10.10-x86_64/wheel
  creating build/bdist.macosx-10.10-x86_64/wheel/tornado
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/__init__.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/auth.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/autoreload.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/concurrent.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/curl_httpclient.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/escape.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/gen.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/http1connection.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/httpclient.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/httpserver.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/httputil.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/ioloop.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/iostream.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/locale.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/locks.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/log.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/netutil.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/options.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado
  creating build/bdist.macosx-10.10-x86_64/wheel/tornado/platform
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/platform/__init__.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado/platform
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/platform/asyncio.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado/platform
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/platform/auto.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado/platform
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/platform/caresresolver.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado/platform
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/platform/common.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado/platform
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/platform/epoll.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado/platform
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/platform/interface.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado/platform
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/platform/kqueue.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado/platform
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/platform/posix.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado/platform
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/platform/select.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado/platform
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/platform/twisted.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado/platform
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/platform/windows.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado/platform
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/process.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/queues.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/simple_httpclient.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/speedups.cpython-35m-darwin.so -> build/bdist.macosx-10.10-x86_64/wheel/tornado
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/stack_context.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/tcpclient.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/tcpserver.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/template.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado
  creating build/bdist.macosx-10.10-x86_64/wheel/tornado/test
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/test/__init__.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado/test
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/test/__main__.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado/test
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/test/asyncio_test.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado/test
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/test/auth_test.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado/test
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/test/concurrent_test.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado/test
  creating build/bdist.macosx-10.10-x86_64/wheel/tornado/test/csv_translations
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/test/csv_translations/fr_FR.csv -> build/bdist.macosx-10.10-x86_64/wheel/tornado/test/csv_translations
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/test/curl_httpclient_test.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado/test
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/test/escape_test.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado/test
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/test/gen_test.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado/test
  creating build/bdist.macosx-10.10-x86_64/wheel/tornado/test/gettext_translations
  creating build/bdist.macosx-10.10-x86_64/wheel/tornado/test/gettext_translations/fr_FR
  creating build/bdist.macosx-10.10-x86_64/wheel/tornado/test/gettext_translations/fr_FR/LC_MESSAGES
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/test/gettext_translations/fr_FR/LC_MESSAGES/tornado_test.mo -> build/bdist.macosx-10.10-x86_64/wheel/tornado/test/gettext_translations/fr_FR/LC_MESSAGES
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/test/gettext_translations/fr_FR/LC_MESSAGES/tornado_test.po -> build/bdist.macosx-10.10-x86_64/wheel/tornado/test/gettext_translations/fr_FR/LC_MESSAGES
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/test/httpclient_test.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado/test
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/test/httpserver_test.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado/test
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/test/httputil_test.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado/test
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/test/import_test.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado/test
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/test/ioloop_test.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado/test
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/test/iostream_test.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado/test
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/test/locale_test.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado/test
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/test/locks_test.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado/test
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/test/log_test.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado/test
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/test/netutil_test.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado/test
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/test/options_test.cfg -> build/bdist.macosx-10.10-x86_64/wheel/tornado/test
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/test/options_test.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado/test
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/test/process_test.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado/test
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/test/queues_test.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado/test
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/test/resolve_test_helper.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado/test
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/test/runtests.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado/test
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/test/simple_httpclient_test.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado/test
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/test/stack_context_test.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado/test
  creating build/bdist.macosx-10.10-x86_64/wheel/tornado/test/static
  creating build/bdist.macosx-10.10-x86_64/wheel/tornado/test/static/dir
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/test/static/dir/index.html -> build/bdist.macosx-10.10-x86_64/wheel/tornado/test/static/dir
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/test/static/robots.txt -> build/bdist.macosx-10.10-x86_64/wheel/tornado/test/static
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/test/static_foo.txt -> build/bdist.macosx-10.10-x86_64/wheel/tornado/test
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/test/tcpclient_test.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado/test
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/test/tcpserver_test.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado/test
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/test/template_test.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado/test
  creating build/bdist.macosx-10.10-x86_64/wheel/tornado/test/templates
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/test/templates/utf8.html -> build/bdist.macosx-10.10-x86_64/wheel/tornado/test/templates
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/test/test.crt -> build/bdist.macosx-10.10-x86_64/wheel/tornado/test
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/test/test.key -> build/bdist.macosx-10.10-x86_64/wheel/tornado/test
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/test/testing_test.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado/test
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/test/twisted_test.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado/test
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/test/util.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado/test
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/test/util_test.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado/test
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/test/web_test.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado/test
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/test/websocket_test.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado/test
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/test/wsgi_test.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado/test
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/testing.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/util.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/web.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/websocket.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado
  copying build/lib.macosx-10.10-x86_64-3.5/tornado/wsgi.py -> build/bdist.macosx-10.10-x86_64/wheel/tornado
  running install_egg_info
  running egg_info
  writing tornado.egg-info/PKG-INFO
  writing dependency_links to tornado.egg-info/dependency_links.txt
  writing top-level names to tornado.egg-info/top_level.txt
  warning: manifest_maker: standard file '-c' not found
  
  reading manifest file 'tornado.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  no previously-included directories found matching 'docs/build'
  warning: no files found matching 'tornado/test/README'
  writing manifest file 'tornado.egg-info/SOURCES.txt'
  Copying tornado.egg-info to build/bdist.macosx-10.10-x86_64/wheel/tornado-4.2.1-py3.5.egg-info
  running install_scripts
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/vy/8gzkm2vj3w72v56yhs6wnmcm0000gn/T/pip-build-uto13tkj/tornado/setup.py", line 173, in <module>
      **kwargs
    File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/Users/thomas/.virtualenvs/tmp-d2a50d26066a1de6/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 213, in run
      archive_basename = self.get_archive_basename()
    File "/Users/thomas/.virtualenvs/tmp-d2a50d26066a1de6/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 161, in get_archive_basename
      impl_tag, abi_tag, plat_tag = self.get_tag()
    File "/Users/thomas/.virtualenvs/tmp-d2a50d26066a1de6/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 155, in get_tag
      assert tag == supported_tags[0]
  AssertionError
  
  ----------------------------------------
  Failed building wheel for tornado
Successfully built keyring
Failed to build tornado
Installing collected packages: Django, django-markwhat, markdown2, argparse, keyring, boto, tornado, colorlog, colorama, six
  Running setup.py install for tornado
Successfully installed Django-1.6.11 argparse-1.4.0 boto-2.38.0 colorama-0.3.3 colorlog-2.6.0 django-markwhat-1.4 keyring-5.6 markdown2-2.3.0 six-1.10.0 tornado-4.2.1
```

Note that tornado is still being installed (and the exit code of the entire process is 0). 

So, I don't think this message isn't a hard failure. If you believe it is, please provide the full output of `pip install ...`. 

In the meantime I'll close the issue, but feel free to add a comment to it and I'll reopen as needed.

---

Also, please note that the entire purpose of having Python 3.5 in our Tox tests (the commit you linked) is to catch issues on 3.5. I don't think the rationale that we shouldn't be testing Python 3.5 unless there are no issues on 3.5 is a very good one.
