### ISSUE TITLE
Cactus won't serve files

### ISSUE THREAD

**Issue by cjrider** [koenbok/Cactus#197]
Hi. Cactus updated itself this morning, now it seems broken.

Reports this error when trying to serve files:

    Traceback (most recent call last):
    File "/Users/cjjr/Applications/Cactus.app/Contents/Resources/python/run.py", line 32, in <module>
    from cactus import cli
    File "/Users/cjjr/Applications/Cactus.app/Contents/Resources/python/CactusSource/cactus/cli.py", line 9, in <module>
    import colorama
    ImportError: No module named colorama

**Comment by cjrider** [comment]
Should say, I'm on Yosemite 10.10.5, running cactus 1.1.18 (the mac GUI, not the naked CLI).

**Comment by federojoavellaneda** [comment]
Hi, me too. ImportError: No module named colorama.

With OSX 10.11 El Capitan

**Comment by mhefferon** [comment]
Hi, I am on Yosemite 10.10.5 and updated cactus as well and getting the "ImportError: No module named colorama. 

![screen shot 2015-10-13 at 10 44 50 am](https://cloud.githubusercontent.com/assets/13139943/10467613/91be5228-71af-11e5-8445-66b33bd53a81.png)

**Comment by danthorpe** [comment]
On El Capitain, Cactus updated to 1.1.18 (436) and I had these problems. I fixed it by doing this...

```
$ pip install colorama
$ pip install django-markwhat
```

If these commands both error due to "Permission denied" just type `sudo !!` to tell the captain you really mean it.

And it now Cactus serves locally. There is still an issue of projects disappearing from the list, #191 mentions this.

**Comment by funkyboy** [comment]
For sake of completeness I tried @danthorpe's solution on 10.10.5 but it doesn't work :)

**Comment by funkyboy** [comment]
In case you wanna go back to previous version this link is still available: http://update.cactusformac.com/static/downloads/Cactus-1.1.15.zip

**Comment by mhefferon** [comment]
@funkyboy I went back to the previous version but now getting a CertificateError. Have you seen this before?

![screen shot 2015-10-14 at 6 04 25 am](https://cloud.githubusercontent.com/assets/13139943/10484402/b83fac14-7239-11e5-8cc6-3be1aeff3641.png)

**Comment by funkyboy** [comment]
@mhefferon sorry no, I don't use the deploy functionality :(

**Comment by dilbertoid** [comment]
I am getting the same error :(

**Comment by L-A** [comment]
@mhefferon @dilbertoid This is Boto failing because it is now too (?) strict on certificate checks – any bucket with a period in its name fails. Boto is the library Cactus uses to manage its communication with S3.

To solve this ,create a `.boto` file in your home (~) directory. It's your local Boto configuration file. It needs these two lines:

```
[s3]
calling_format = boto.s3.connection.OrdinaryCallingFormat
```

Afterwards, deployment from Cactus.app should work as expected. Hopefully, this is temporary.

Gist for reference: https://gist.github.com/L-A/480a1e8b46fdb4fd6537
