### ISSUE TITLE
cactus serve fails

### ISSUE THREAD

**Issue by OnlinePage** [koenbok/Cactus#286]
Hi I tried using the cactus on anaconda with python 3.9

with command  `cactus create` it easily creates the files and all
now when doing `cactus serve` for first time on the created base project it throws below error

`Unable to import requested engine (S3DeploymentEngine) for provider aws
Traceback (most recent call last):
  File "C:\Users\pranj\anaconda3\lib\site-packages\cactus\deployment\__init__.py", line 32, in get_deployment_engine_class
    _mod = __import__(module, fromlist=[engine])
  File "C:\Users\pranj\anaconda3\lib\site-packages\cactus\deployment\s3\engine.py", line 10, get_deployment_engine_class(hosting_provider)
  File "C:\Users\pranj\anaconda3\lib\site-packages\cactus\deployment\__init__.py", line 35, in get_deployment_engine_class
    logger.error("A required library was missing: %s", e.message)
AttributeError: 'ImportError' object has no attribute 'message'
`

**Comment by joelhaasnoot** [comment]
The full stack trace is actually
```
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/cactus/deployment/__init__.py", line 32, in get_deployment_engine_class
    _mod = __import__(module, fromlist=[engine])
  File "/opt/homebrew/lib/python3.10/site-packages/cactus/deployment/s3/engine.py", line 10, in <module>
    from cactus.deployment.s3.auth import AWSCredentialsManager
  File "/opt/homebrew/lib/python3.10/site-packages/cactus/deployment/s3/auth.py", line 2, in <module>
    from cactus.deployment.auth import BaseKeyringCredentialsManager
  File "/opt/homebrew/lib/python3.10/site-packages/cactus/deployment/auth.py", line 4, in <module>
    import keyring
  File "/opt/homebrew/lib/python3.10/site-packages/keyring/__init__.py", line 12, in <module>
    from .core import (set_keyring, get_keyring, set_password, get_password,
  File "/opt/homebrew/lib/python3.10/site-packages/keyring/core.py", line 13, in <module>
    from . import backend
  File "/opt/homebrew/lib/python3.10/site-packages/keyring/backend.py", line 22, in <module>
    from .util import properties
  File "/opt/homebrew/lib/python3.10/site-packages/keyring/util/properties.py", line 1, in <module>
    from collections import Callable
ImportError: cannot import name 'Callable' from 'collections' (/opt/homebrew/Cellar/python@3.10/3.10.17/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/bin/cactus", line 8, in <module>
    sys.exit(cli_entrypoint())
  File "/opt/homebrew/lib/python3.10/site-packages/cactus/cli.py", line 159, in cli_entrypoint
    main(sys.argv[1:])
  File "/opt/homebrew/lib/python3.10/site-packages/cactus/cli.py", line 155, in main
    ns.target(**kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/cactus/cli.py", line 49, in build
    site = self.Site(path, config)
  File "/opt/homebrew/lib/python3.10/site-packages/cactus/site.py", line 89, in __init__
    DeploymentEngineClass = get_deployment_engine_class(hosting_provider)
  File "/opt/homebrew/lib/python3.10/site-packages/cactus/deployment/__init__.py", line 35, in get_deployment_engine_class
    logger.error("A required library was missing: %s", e.message)
AttributeError: 'ImportError' object has no attribute 'message'
```
It seems cactus is incompatible with Python 3.10

**Comment by Huaian666** [comment]
finally something that doesn't try to do everything. does one thing, does it well, gets out of your way. respect.
